import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Footer";
import "./globals.css";
import { Header } from "@/components/Header";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="container h-screen flex flex-col justify-between m-auto">
          <Header />
          <StoreProvider>
            <main>{children}</main>
          </StoreProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
